### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zhengjunzhuzhu** [ArcherFMY/HCA_saliency_codes#1]
其中的res只是定义了全局变量，未对res赋值，在
 FCNfeat.pool1           =   res{pool1_ind};句会报错，元胞内容引用自非元胞数组对象。
res完全是空的，想请教您一下这个地方应该怎么办

**Comment by ArcherFMY** [comment]
@zhengjunzhuzhu We modified the matconvnet-1.0-beta19/matlab/+dagnn/@DagNN/eval.m, adding global variable 'res', to allow users to extract features from every layers (conv, pool, relu). So if you are using your own matconvnet, please modify the corresponding .m file as we did. See details in https://github.com/ArcherFMY/HCA_saliency_codes/blob/master/matconvnet-1.0-beta19/matlab/%2Bdagnn/%40DagNN/eval.m
